### ISSUE TITLE
Broken link in Readme

### ISSUE THREAD

**Issue by abrock** [jlblancoc/nanoflann#106]
The readme links to this site:
http://people.cs.ubc.ca/~mariusm/index.php/FLANN/FLANN

Which seems to have moved to
http://www.cs.ubc.ca/research/flann/

The code is on github now so you could link to that too:
https://github.com/mariusmuja/flann

**Comment by abrock** [comment]
The link to libkdtree++ is broken, too. alioth.debian.org was deprecated and decommissioned some time ago.

**Comment by jlblancoc** [comment]
fixed, thanks!
