### ISSUE TITLE
Library version number not updated on release 1.3.1

### ISSUE THREAD

**Issue by erikdendekker** [jlblancoc/nanoflann#115]
Both in git master and tag 'v1.3.1' the version of the library is defined as:

```
nanoflann.hpp:61: /** Library version: 0xMmP (M=Major,m=minor,P=patch) */
nanoflann.hpp:62: #define NANOFLANN_VERSION 0x130
```

while in tag 'v1.3.1' it should be defined as 0x131,.. I am unsure how it should be defined in master

**Comment by jlblancoc** [comment]
Ooops... you're totally right! 

It's fixed now... tag `v1.3.1` has been moved (`--force`... sorry for that) , and version in master is `v1.3.2`.
