### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by SirNova01** [jlblancoc/nanoflann#118]
CMake Error at /home/sirnova/Music/deepsdf/DeepSDF/build/nanoflann/nanoflannConfig.cmake:27 (include):
  include could not find load file:

    nanoflann/nanoflannTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)

CMake Error at /home/sirnova/Music/deepsdf/DeepSDF/build/nanoflann/nanoflannConfig.cmake:11 (message):
  File or directory nanoflann/include referenced by variable
  nanoflann_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  /home/sirnova/Music/deepsdf/DeepSDF/build/nanoflann/nanoflannConfig.cmake:29 (set_and_check)
  CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/sirnova/Desktop/CmakeTut/cmake-tutorial/build/CMakeFiles/CMakeOutput.log"

**Comment by korrix** [comment]
I had the same problem yesterday, try building your library with:
```
cd directory_with_nanoflann
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="nanoflann_install_directory" ..
cmake --build . --config Release --target install
```

Later add the `nanoflann_install_directory` to CMAKE_PREFIX_PATH of your actual project
