### ISSUE TITLE
Respect CMake's GNUInstallDirs?

### ISSUE THREAD

**Issue by mablanchard** [jlblancoc/nanoflann#129]
It seems like nanoflann CMake build scripts currently [hard-codes installation directories](https://github.com/jlblancoc/nanoflann/blob/master/CMakeLists.txt#L50). CMake's [`GNUInstallDirs`](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) module defines standards for their locations (which defaults already match nanoflann ones). Using it would simplify integration of the library in complex software stacks where build is automated I believe.

**Comment by mablanchard** [comment]
I could work on a patch if the project is willing to accept such an enhancement.

**Comment by jlblancoc** [comment]
Oh, sure! We use GNUInstallDirs in most other projects. Please, go ahead and propose a PR.
Thanks!
