### ISSUE TITLE
Points movement

### ISSUE THREAD

**Issue by j8asic** [jlblancoc/nanoflann#13]
If some or all points changed coordinates, is it somehow possible to reinsert them in same tree structure (without rebuilding)?

E.g. I have transient simulation of point cloud (with known bounds) and would like to rebuild whole tree on every N-th step, else just reinsert moving points into already built hierarchy.

**Comment by jlblancoc** [comment]
No, you should rebuild the tree. 

If *all* points rotate at once, consider changing the coordinates of the query points, keeping the kd-trees relative to a local frame of the point cloud...
