### ISSUE TITLE
[BUG] KDTreeVectorOfVectorsAdaptor compiling failure with custom IndexType

### ISSUE THREAD

**Issue by ro0o0o0okie** [jlblancoc/nanoflann#135]
Due to the miss of passing parent template argument **IndexType** in the **self_t** definition, [**this line**](https://github.com/jlblancoc/nanoflann/blob/88d5dc44e8edf4317a88fc9a9c2c1dd845564810/examples/KDTreeVectorOfVectorsAdaptor.h#L52)  will cause compiling failure when **IndexType** is not **self_t**.

The fix will be:
change 
```cpp
typedef KDTreeVectorOfVectorsAdaptor<VectorOfVectorsType, num_t, DIM, Distance> self_t;
```
into 
```cpp
typedef KDTreeVectorOfVectorsAdaptor<VectorOfVectorsType, num_t, DIM, Distance, IndexType> self_t;
```

**Comment by jlblancoc** [comment]
Please, reopen if still an issue with the latest release. Thanks!
