### ISSUE TITLE
Are there some reference paper about this repository?

### ISSUE THREAD

**Issue by Gatsby23** [jlblancoc/nanoflann#136]
Hi, I'm a fresh man to the KD-Tree algorithm. After I test the classical repository about KD-Tree on github, I think this repository is the best to implement KD-Tree algorithm. But I want to know why this repository can reduce the memory cost and improve the performance？ Is there some reference paper recommend to read？

**Comment by jlblancoc** [comment]
Hi, 
It's embarrassing to admit but... nope, there is none! Never found time to write a proper paper for nanoflann (it's been in my list for... years). 

You could refer to others who ran benchmarks with it, though, e.g.

```bibtex
@article{vermeulen2017comparative,
  title={A comparative study of k-nearest neighbour techniques in crowd simulation},
  author={Vermeulen, Jordi L and Hillebrand, Arne and Geraerts, Roland},
  journal={Computer Animation and Virtual Worlds},
  volume={28},
  number={3-4},
  pages={e1775},
  year={2017},
  publisher={Wiley Online Library}
}

@article{juba2016acceleration,
  title={Acceleration and parallelization of zeno/walk-on-spheres},
  author={Juba, Derek and Keyrouz, Walid and Mascagni, Michael and Brady, Mary},
  journal={Procedia computer science},
  volume={80},
  pages={269--278},
  year={2016},
  publisher={Elsevier}
}
```
and probably others.

On the reasons for efficiency, take a look at the README file. One of the most important design decisions were to avoid copying data at all by using proxy data source classes. Less dynamic memory is *always* better ;-)

**Comment by Gatsby23** [comment]
> Hi,
> It's embarrassing to admit but... nope, there is none! Never found time to write a proper paper for nanoflann (it's been in my list for... years).
> 
> You could refer to others who ran benchmarks with it, though, e.g.
> 
> ```
> @article{vermeulen2017comparative,
>   title={A comparative study of k-nearest neighbour techniques in crowd simulation},
>   author={Vermeulen, Jordi L and Hillebrand, Arne and Geraerts, Roland},
>   journal={Computer Animation and Virtual Worlds},
>   volume={28},
>   number={3-4},
>   pages={e1775},
>   year={2017},
>   publisher={Wiley Online Library}
> }
> 
> @article{juba2016acceleration,
>   title={Acceleration and parallelization of zeno/walk-on-spheres},
>   author={Juba, Derek and Keyrouz, Walid and Mascagni, Michael and Brady, Mary},
>   journal={Procedia computer science},
>   volume={80},
>   pages={269--278},
>   year={2016},
>   publisher={Elsevier}
> }
> ```
> 
> and probably others.
> 
> On the reasons for efficiency, take a look at the README file. One of the most important design decisions were to avoid copying data at all by using proxy data source classes. Less dynamic memory is _always_ better ;-)

Thanks! Great Work!
