### ISSUE TITLE
[Question] Any beginner guide / tutorial on using nanoflann?

### ISSUE THREAD

**Issue by YashBansod** [jlblancoc/nanoflann#141]
Hi folks,

I recently came across this project and this seems really useful for building KD Trees for a RRT algorithm implementation I am attempting.
However, I have been struggling to understand how to use this library properly. 

**Is there and starter guide for this project?**

**Comment by jlblancoc** [comment]
Nope, there is not... The closest are the examples provided [here](https://github.com/jlblancoc/nanoflann/tree/master/examples). Take a look there, hopefully they will guide you in your way... 
Best,
