### ISSUE TITLE
[Question] How to find NN for vector of custom struct?

### ISSUE THREAD

**Issue by YashBansod** [jlblancoc/nanoflann#143]
I have a data structure `CustomVec`:
```c++
struct CustomNode{
    string name;
    double x, y;
    int extra_val;
    CustomNode() : name("custom"), x(0.0), y(0.0), extra_val(0) {};
    CustomNode(const string& _n, double _x, double _y, int _e) : name(_n), x(_x), y(_y), extra_val(_e) {};
};
typedef vector<CustomNode> CustomVec;
```

I want to find the `CustomNode` {say `NodeA`} in `CustomVec` closest to a newly created `CustomNode` {say `NodeB`}.
The distance can be calculated using the formula:
```c++
double dist = pow(NodeA.x - NodeB.x, 2) + (NodeA.y - NodeB.y, 2);
```

Can someone provide me the overview of steps I need to do to achieve this using this KD tree library?

Do I have to write a new Adapter code for this?

**Comment by jlblancoc** [comment]
Hi Yash, 

Yes, for custom data types you'll have to either write your own adapter, or convert the data into one of the provided adapter examples (obviously, with a copy cost...).
