### ISSUE TITLE
radiusSearch requires square of distance 

### ISSUE THREAD

**Issue by prashjha** [jlblancoc/nanoflann#145]
Hi,

Thanks for this library. I have been using the PCL library for tree search but nanoflann is much much more convenient. 

I think in `radiusSearch()`, nanoflann asks for the square of `r`, where `r` is a search radius.  If I want points `y` in list `X` which are within `r` distance of another point `x_0`, then I should use `radiusSearch()` as follows:
```c++
radiusSearch(x_0, r*r, ...)
```
Does this sound correct?

**Comment by kzampog** [comment]
Correct, that's also documented in the README

**Comment by prashjha** [comment]
Great. Somehow I missed this bit in README. Thanks for clarifying. :)
