### ISSUE TITLE
Bounding Box Result Set

### ISSUE THREAD

**Issue by JadTawil-theonly** [jlblancoc/nanoflann#147]
Hello All,,

I've used the radius result set and k nearest neighbor sets. 

But lets say instead of radius, i want to find the elements that are within a bounding box centered at some coordinate (xyz).

How would this be done?

I am guessing i have to create my own result set?

**Comment by JadTawil-theonly** [comment]
I would like to implement the following distance metric between a query point the cloud of points:
where x, y, z is x_query - x_point,  y_query - y_point, and z_query-z_point, respectively.
and c1, c2, c3, are coefficients that normalize the distance such that any point within the box with dimensions c1, c2, c3, centered around query point, will have a distance < 1.

distance = max(((x/c1)^2), ((y/c2)^2), ((z/c3)^2))

any ideas?

**Comment by jlblancoc** [comment]
Sorry for the late answer...

Yes, you'll have to create either a custom ResultSet, or a distance metric class that maps distances such that, say, those within the bounding box have a distance smaller than 1, then do a radius query for "1". 
See the [new example](https://github.com/jlblancoc/nanoflann/blob/master/examples/pointcloud_custom_metric.cpp) as a starting point.
