### ISSUE TITLE
in my case, nanoflann is slower than pcl flann

### ISSUE THREAD

**Issue by leechangyo** [jlblancoc/nanoflann#150]
i have fixed pointclouds 21,000 and streaming pointcloud.

and search matching point between them using nano flann and pcl flan.

and in my case, pcl flann is faster than nano flann(around 10ms).

if i turn addpoints into false, it become much faster than pcl flan(around 10ms) but there is a lot of noise exists.

how to make faster and high accuracy?

**Comment by jlblancoc** [comment]
False alarm? :-)
