### ISSUE TITLE
Switching to C++ streams for save/load operations

### ISSUE THREAD

**Issue by dokempf** [jlblancoc/nanoflann#156]
NanoFLANN is a C++ library, but uses C file handles for the `{load, save}Index` methods, which is slightly odd. On my fork, I have implemented C++ streams and I am willing to contribute this if you are interested: https://github.com/dokempf/nanoflann/pull/1/files. FWIW, my reason to do so was to use `std::stringstream` for pickling support in Python bindings to a NanoFLANN data structure.

**Comment by jlblancoc** [comment]
Good point :+1:
Sure, go on and open a pull request and I'll review it. 
BTW: I think it would be more general if the load/save functions take `std::istream` and `std::ostream` (using `#include <iosfwd>` only if possible to maximize build speed). Make sure of clearly specifying in the methods documentation (Doxygen preamble) whether the serialization is in text or binary format.

Thanks!
