### ISSUE TITLE
Is it safe to append to the adaptor dataset?

### ISSUE THREAD

**Issue by clarkholdham** [jlblancoc/nanoflann#158]
I'm using a tree to merge 2 datasets and would like to avoid making a copy of either dataset if possible. I'm wondering if I can append to the adaptor dataset and continue to search with the tree. I seems the initial size is stored and used as a bound but I want to be sure.

**Comment by jlblancoc** [comment]
Once built, the tree index only keeps indices. It's up to your adaptor to map those indices to where the data is actually stored. 

If your adaptor only accesses the data via `[]` or `at()` operators, for example, it's totally safe to expand the container.... though the kd-tree index won't know about the new data points, of course! :-)

**Comment by clarkholdham** [comment]
This is exactly my scenario, thank you!

**Comment by jlblancoc** [comment]
:+1:
