### ISSUE TITLE
How to setup a user defined metric with argument

### ISSUE THREAD

**Issue by ChiaCheng-Tsai** [jlblancoc/nanoflann#160]
Dear nanoflann friends?

I try to copy the L2_Simple_Adaptor and metric_L2_Simple to my own metric. However, I cannot figure how to put a parameter into this user-defined metric. To be more specific, my user-defined metric is dependent on a parameter which will be determined at run-time. Any of yor response will be highly appreciated, and

best regard
CC Tsai

**Comment by jlblancoc** [comment]
Closed via c0d63a7d418117738ffaa0f9042fab86474587fc

It was actually not possible in an "elegant" way, so I just provided that feature and an example in the commit above.

Cheers,
