### ISSUE TITLE
Unused private field

### ISSUE THREAD

**Issue by vidstige** [jlblancoc/nanoflann#17]
Compiling with flann I get the following warning (translated to error by `-Werror`)

    nanoflann.hpp:468:11: error: private field 'blocksize' is not used [-Werror,-Wunused-private-field]
                     size_t  blocksize;
                             ^

**Comment by jlblancoc** [comment]
Hi, 

It is strange... do you refer to this line? (the line numbers do not match): 

https://github.com/jlblancoc/nanoflann/blob/2485d57279c016e27aaf6e8905cabcabf48e17e8/include/nanoflann.hpp#L535

There, `blocksize` *is* used..

**Comment by vidstige** [comment]
Very strange, if I look now at the latest master there is no private field anywhere called `blocksize`. I should probably just upgrade. I'm using 1.1.8 right now.

**Comment by vidstige** [comment]
That's your latest released version though? Would you consider making a new release?

**Comment by jlblancoc** [comment]
:+1: 

Done!

**Comment by vidstige** [comment]
Thank you :)
