### ISSUE TITLE
bug report: memory corruption

### ISSUE THREAD

**Issue by AndreyMlashkin** [jlblancoc/nanoflann#179]
in the constructor of KDTreeSingleIndexAdaptor, you expect inputData lifetime should be longer rather then Adaptor itself, but it is not always true and user of the code can easily break it.

```    template <class... Args>
    KDTreeSingleIndexAdaptor(
        const Dimension dimensionality, const DatasetAdaptor& inputData,
        const KDTreeSingleIndexAdaptorParams& params = {}, Args&&... args)
        : dataset(inputData),
          index_params(params),
          distance(inputData, std::forward<Args>(args)...)
    {
```

for exmple, calling this would cause indefined behaviour:  
    ModelKDTreeIndex index(2, std::vector<Vector2f> {}, nanoflann::KDTreeSingleIndexAdaptorParams(10));

**Comment by AndreyMlashkin** [comment]
@jlblancoc ping

**Comment by jlblancoc** [comment]
Merged #180. I'll however leave this one open to remember to add a comment to that ctor warning the users about expected lifetimes. 
Thanks.

**Comment by AndreyMlashkin** [comment]
Thanks!
Could you also ping me somehow, I will also create a new version of nanoflan in conan package manager.

**Comment by jlblancoc** [comment]
@AndreyMlashkin  
New release is out! => https://github.com/jlblancoc/nanoflann/releases/tag/v1.4.3

Thanks!
