### ISSUE TITLE
Applying rigid/nonrigid transformations to the tree

### ISSUE THREAD

**Issue by Frudel** [jlblancoc/nanoflann#18]
Is it possible to apply transformations (rotation/translation/scaling) to the entire tree without rebuilding the index? If yes, this might be a nice feature for increasing speed.

**Comment by jlblancoc** [comment]
Hi Frudel, 

In my opinion, this feature is not needed: if you really need to transform the *entire* tree, then it will be much easier to apply the *inverse transformation* to the query points, then query the original tree...
