### ISSUE TITLE
Does it support 6D NN Search?

### ISSUE THREAD

**Issue by YingGwan** [jlblancoc/nanoflann#192]
Hi Sir/Madam,

I have a question about this library: Does it support 6d flann search? Considering I have xyzrgb to consider, how can I directly use your code to achieve this functionality?

Many thanks!
Yingjun

**Comment by YingGwan** [comment]
I changed Struct PointCloud in utils.h and solved the problem. The efficiency is quite high. 

It has been achieved 35X faster than brute-force method.

**Comment by jlblancoc** [comment]
Good! 👍
