### ISSUE TITLE
How to add KDTree into a hashset/hashmap?

### ISSUE THREAD

**Issue by JiayingGaoo** [jlblancoc/nanoflann#204]
Hi there,
Thanks for your great and impressive work!
I am new to nanoflann. I want to add some kdtree into a hashset, just like below:

`
using KDTree = KDTreeSingleIndexAdaptor<L2_Simple_Adaptor<double, Point2D<double>>, Point2D<double>, 2/* dim */>;
KDTree kd0 = KDTree(2, cloud0);
KDTree kd1 = KDTree(2, cloud1);
KDTree kd2 = KDTree(2, cloud2);

unordered_set<KDTree> trees = {kd0, kd1, kd2};
`

Then, a mistake is encountered: 
error C2440: 'initializing': cannot convert from 'initializer list' to 'std::unordered_set<KDTRee,std::hash<KDTRee>,std::equal_to<KDTRee>,std::allocator<KDTRee>>'

What can i do to fix it, thanks a lot!

**Comment by JiayingGaoo** [comment]
Maybe I need to construct the hashset by the pointers, such like: unordered_set<KDTree*>?

**Comment by JiayingGaoo** [comment]
Thanks, I solve it.

**Comment by jlblancoc** [comment]
Cool! Yeah, using pointers is a possible solution. Another is creating your own overload of hash. 
Read, for example, [this SO thread](https://stackoverflow.com/questions/38554083/how-can-i-use-a-c-unordered-set-for-a-custom-class).
