### ISSUE TITLE
Segfault when saving index built from empty array

### ISSUE THREAD

**Issue by h4k1m0u** [jlblancoc/nanoflann#205]
Not sure if it's the expected behavior of nanoflann and since it wasn't mentioned in the docs, I thought it was worth raising up this issue.
I pass 3D point coordinates to nanoflann to construct the kdtree index (distance = L2). When the number of points is = 0 and I try to save the index, I get a segfault from the second line in the following:

```cpp
std::ofstream file_kdtree(path_kdtree, std::ofstream::binary);
index.saveIndex(file_kdtree);
```

To avoid the segfault, I don't call `m_index.saveIndex()` unless `index.m_size > 0`.

**Comment by jlblancoc** [comment]
Indeed, it was a bug. Fixed now, thanks!
