### ISSUE TITLE
Support KNN search within radius

### ISSUE THREAD

**Issue by kya8** [jlblancoc/nanoflann#216]
A.K.A "hybrid search" or "RKNN". It's essentially KNN guarded by a max radius, which can be useful in some cases.

[Open3D](http://www.open3d.org/docs/latest/tutorial/Basic/kdtree.html#Using-search_radius_vector_3d) for example, implements this functionality.

To support it within `nanoflann` seems to be trivial, we can simply set the max radius here:  
https://github.com/jlblancoc/nanoflann/blob/92bae2a0f44e3a29e720c751866b1eeb36416baf/include/nanoflann.hpp#L189C15-L189C15
We could add a radius parameter to the constructor of `KNNResultSet`, or `KNNResultSet::init()`, or add a separate method.

Currently I just copy the header and add my own RKNN `ResultSet`, and it works as expected. It would be nice if RKNN can be supported upstream.

**Comment by jlblancoc** [comment]
I'll add it. We also found this need recently in another derived project
