### ISSUE TITLE
KDTreeEigenMatrixAdaptor Build Index Issue after the Update 1.5.0

### ISSUE THREAD

**Issue by mauzaomin** [jlblancoc/nanoflann#233]
Hi,

Not sure if it worth taking a look. I'm not able to build a tree per the example in the documentation below after the update 1.5.0. Example below still works if I use version 1.4.3

Error Message from g++ 13.2.0
![Capture](https://github.com/jlblancoc/nanoflann/assets/19234784/3217f3c3-2183-4605-bafc-852359912da0)

Eigen::Matrix<num_t,Dynamic,Dynamic>  mat;
// Fill out "mat"...
typedef KDTreeEigenMatrixAdaptor< Eigen::Matrix<num_t,Dynamic,Dynamic> >  my_kd_tree_t;
const int max_leaf = 10;
my_kd_tree_t   mat_index(dimdim, mat, max_leaf );
mat_index.index->buildIndex();
mat_index.index->...

**Comment by jlblancoc** [comment]
Yes, just use the member named "index_" instead of "index", it was changed long time ago to comply with common naming practices...
