### ISSUE TITLE
findNeighbors does not sort results 

### ISSUE THREAD

**Issue by ThibaultLejemble** [jlblancoc/nanoflann#245]
When performing radius search with `findNeighbors` (https://github.com/jlblancoc/nanoflann/blob/3900193f7e200c9e152aa4b240d7eca47a830a80/include/nanoflann.hpp#L1661C10-L1661C23),
resulting indices are not sorted with respect to the distance to the query point, 
even though the default `SearchParameters` given as parameter has its boolean member `SearchParameters::sorted` set to `true`. 

I believe this sorting option is only used by the other query function `radiusSearch`.

It may not be a bug, but I found the usage of this function quite misleading and a warning might be needed in the documentation.

Here is a piece of code I added to `examples/pointcloud_kdd_radius.cpp` to check that the result is not sorted:
```c++
    {
        const num_t search_radius = static_cast<num_t>(0.1);
        std::vector<nanoflann::ResultItem<uint32_t, num_t>> ret_matches;

        std::vector<nanoflann::ResultItem<size_t, num_t>> indices_dists;
        nanoflann::RadiusResultSet<num_t, size_t> resultSet( search_radius, indices_dists );
        nanoflann::SearchParameters searchParams;
        searchParams.sorted = true;
        const bool status = index.findNeighbors(resultSet, &query_pt[0], searchParams);
    
        cout << "findNeighbors(): radius=" << search_radius << " -> " << status
             << " \n";
        for (size_t i = 0; i < resultSet.size(); i++)
            cout << "idx[" << i << "]=" << resultSet.m_indices_dists[i].first << " dist[" << i
                 << "]=" << resultSet.m_indices_dists[i].second << endl;
        cout << "\n";
    }
```

**Comment by jlblancoc** [comment]
Thanks for spotting this one! 
Indeed, it was totally misleading to have the "sorted" parameter and then not using it. 
It's fixed now via https://github.com/jlblancoc/nanoflann/commit/a74fc3b5b359c941d9a00eb9d92c2202c22eca3a
and a new unit test added to cover this case.
The fix will ship now in v1.6.0
