### ISSUE TITLE
Segment fault while release KDTreeVectorOfVectorsAdaptor

### ISSUE THREAD

**Issue by thuhuwei** [jlblancoc/nanoflann#25]
I compiled the example vector_of_vectors successfully. However, I got the segment fault message before the application exited.  I found that it is caused by releasing the KDTreeVectorOfVectorsAdaptor structure.
I use the code of the master branch. My OS is ubuntu 14.04. Could you give me some advises? Thanks.

the error message:

Generating 1000 random points...done
knnSearch(nn=3): 
ret_index[0]=46 out_dist_sqr=476.232
ret_index[1]=869 out_dist_sqr=490.892
ret_index[2]=660 out_dist_sqr=493.263
Segment fault(core dumped)

**Comment by jlblancoc** [comment]
Thanks! After investigating a while, I discovered it had to do with the storage of `const` by value instead of `const ref`'s in several spots. It's fixed now after https://github.com/jlblancoc/nanoflann/commit/d3e31869779890ab1bf9ca753807ce496f21501b
