### ISSUE TITLE
clarification: approximation or exact search?

### ISSUE THREAD

**Issue by kmgl** [jlblancoc/nanoflann#27]
When looking at your description I was wondering whether this library uses kd-trees to determine exact results in the knn and radius search or if there are approximations? For me it looks that you do not perform approximations; which would make sense for low-dimensional point-clouds.

**Comment by jlblancoc** [comment]
Hi @kmgl , 

The original FLANN library included approximated (hence the **A**) methods, but nanoflann does only exact searches. Let me know if there is some confusing part in the docs regarding this point...

**Comment by kmgl** [comment]
Thank you very much  @jlblancoc , for the clarification.
I guess the confusing part is that the library is called nanofl**a**nn (with the A), which I understand since it is based on FLANN. In the brief description it says:  

> nanoflann: a C++ header-only library for Nearest Neighbor (NN) search wih KD-trees

which indicates that it is without the approximation. You referred in the description to ANN algorithms (based on the original paper) and I had a look at the original paper and the main contribution of that paper is the approximation but than again your description also says: 

> There is no automatic algorithm configuration (as described in the original Muja & Lowe's paper).

which further indicates that you don't perform approximation. Maybe a clarifying statement in the:
Section:

> 1.5. What can nanoflann do?

might be also useful for others. I just wanted to make sure that my assumption that your library provides exact queries is correct. Since I want to use it for broadphase collision avoidance. Thank you again for the clarification.

**Comment by jlblancoc** [comment]
Ok, thanks for the feedback! I've just updated the README.

**Comment by codingforfun** [comment]
Hi, 
I was stumbling over the exact same question. From the README I got the idea that this library most probably does exact searches, but anyway wasn't not 100% sure. So maybe you could even make a stronger statement about this in the README to make this really 100% clear. Thx.
