### ISSUE TITLE
Getting nanoflann/examples/KDTreeVectorOfVectorsAdaptor.h to work

### ISSUE THREAD

**Issue by pinaky** [jlblancoc/nanoflann#30]
In file: nanoflann/examples/KDTreeVectorOfVectorsAdaptor.h

Here are some things that might need changing:
1) **Line 54**:  `typedef KDTreeSingleIndexAdaptor< metric_t,self_t,DIM,IndexType>  index_t;`
**Solution**: Need to reference the namespace, so perhaps change it to: `typedef nanoflann::KDTreeSingleIndexAdaptor`

2) **Line 82**: `nanoflann::KNNResultSet<typename VectorOfVectorsType::Scalar,IndexType> resultSet(num_closest);` in `inline void query`:
If `VectorOfVectorsType` is `std::vector<std::vector<double> >`, then it will complain that no member `::Scalar` exists. I think you intended that for `Eigen::VectorXd`.
**Solution**: I got this to work by changing it to `num_t`

**Comment by jlblancoc** [comment]
Thanks! It makes sense... 
Please, feel free of opening a pull-request with those exact changes, so you can be sure that they are included exactly as you have tested them (and to keep you as a contributor for the records!).

**Comment by pinaky** [comment]
Awesome. Thanks will do

**Comment by pinaky** [comment]
I've applied the changes and issued a pull request. The pull request status says: "Failure: The Travis CI build failed". Do these changes conflict with some other part of the code?
