### ISSUE TITLE
knnSearch returns invalid results when number of elements in the tree is smaller than num_results

### ISSUE THREAD

**Issue by ninopereira** [jlblancoc/nanoflann#32]
When performing a search for a maximum of k nearest points using the function knnSearch, we get invalid results if the number of elements on the tree is less than the requested number of results (num_results).

**Comment by jlblancoc** [comment]
Fixed with https://github.com/jlblancoc/nanoflann/commit/206d65a8498a8dfb1910ac8d3de893286fa89e9a

Check the changes to the example code as well to see a way to handle this situation. 
Thanks for reporting!
