### ISSUE TITLE
Support add/remove items from the tree

### ISSUE THREAD

**Issue by jlblancoc** [jlblancoc/nanoflann#4]
Add support for add/remove points, with selective tree-rebuild.

**Comment by ColinGilbert** [comment]
Out of curiosity, I have been seeking a fast way to do nearest neigbours on dynamic data too; which data structure do you intend on using?

**Comment by jbensabat** [comment]
we needs trees for the 2D sets of points (point generation as a first step of mesh generation) and particle tracking

**Comment by ColinGilbert** [comment]
Ok. Somewhat related: Is there currently a feasible way of rebuilding only the part of the tree that changes? (Aside from building several nanoflann instances, that is.)

**Comment by jbensabat** [comment]
no idea

**Comment by bradrothenberg** [comment]
Was this added?

**Comment by jlblancoc** [comment]
Sorry, but it is still in my to-do list... (now focused on finishing [another project](https://github.com/MRPT/srba))

For the records: the theory behind this feature will be the logarithmic method: http://www.cse.cuhk.edu.hk/~taoyf/course/wst501/notes/lec11.pdf

**Comment by ataiya** [comment]
+1

**Comment by giorgiomarcias** [comment]
+1

**Comment by anlif** [comment]
👍  :)

I would like this feature for clustering radar data in real time.

**Comment by jbensabat** [comment]
good morning 
is there any progress on this ?
thanks

**Comment by CharlieShi** [comment]
+1
really looking forward to it

**Comment by dfridovi** [comment]
Any updates on this?

**Comment by jlblancoc** [comment]
Not yet, sorry. Still have other projects with much higher priorities...

We're proposing this to be a possible task for GSoC2017:
https://github.com/MRPT/mrpt/wiki/Ideas-page-for-MRPT-Google-Summer-of-Code-2017

**Comment by jlblancoc** [comment]
For the records: Working on this idea was finally accepted as part of one project in GSoC 2017:

[Algorithm improvements to KD-Tree module: applications to ICP](https://github.com/MRPT/GSoC2017-discussions/issues/1).

**Comment by jlblancoc** [comment]
Was about time... this feature has been added in PR #48 by @pranjal-rai . 
We'll soon merge the changes into master, so tests and feedback will be more than welcome.
