### ISSUE TITLE
nanoflann CMake file does not support the use of target_link_libraries

### ISSUE THREAD

**Issue by limdor** [jlblancoc/nanoflann#41]
When nanoflann is used from a different project using CMake, the user of this project cannot use nanoflann using target_link_libraries.
In order to do this what it needs to be done is to update the CMakeLists.txt to support a more modern way of using CMake.
Specially what is missing is:
```
add_library(nanoflann INTERFACE)

target_include_directories(nanoflann
	INTERFACE
		$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
		$<INSTALL_INTERFACE:${INCLUDE_INSTALL_DIR}>/include)
```

And then this should be removed:
`INCLUDE_DIRECTORIES(${nanoflann_SOURCE_DIR}/include)`

**Comment by jlblancoc** [comment]
Thanks for the pointers, @limdor !
