### ISSUE TITLE
Thread-safe?

### ISSUE THREAD

**Issue by r-barnes** [jlblancoc/nanoflann#54]
Is nanoflann thread-safe under (apparently) read-only operations?

**Comment by jlblancoc** [comment]
Yes, querying a kd-tree is thread safe. I've updated the docs. If you happen to find any issue on this regards, please report it back. Cheers.

**Comment by r-barnes** [comment]
Thanks! When querying a kd-tree in OpenMP while using address sanitizer, I get warnings about memory being accessed out of scope. It looks like a false positive induced by the introduction of the parallel section, but I haven't yet found a sanitizer caveat about this.
