### ISSUE TITLE
dead code?

### ISSUE THREAD

**Issue by ibtaylor** [jlblancoc/nanoflann#55]
I'm confused by this function. Nothing ever seems to call it. 

https://github.com/jlblancoc/nanoflann/blob/e687af03e85ce2e5907c0453998ba3cb870e02b3/include/nanoflann.hpp#L1962-L1971

Seems like it wasn't fully cleared out during this commit.
https://github.com/jlblancoc/nanoflann/commit/b83c291bd49115d8813dae4ac2f77fdab6ef2d6e#diff-6972321bb8a18bf106257beeecb4a09eL371

**Comment by jlblancoc** [comment]
@ibtaylor thanks!! You were right... It's clear that this code was useless, specially since there is a template argument for the type of metric, and this old code was only for L2. 

All good 👍
