### ISSUE TITLE
std::log2 not found

### ISSUE THREAD

**Issue by keithbriggs** [jlblancoc/nanoflann#61]
kbriggs:~/tests> g++ -Wall -I ~/Downloads/nanoflann-master/include/ -I ~/Downloads/nanoflann-master/examples pointcloud_kdd_radius.cpp -o pointcloud_kdd_radius
In file included from pointcloud_kdd_radius.cpp:31:0:
/home/kbriggs/Downloads/nanoflann-master/include/nanoflann.hpp: In constructor ‘nanoflann::KDTreeSingleIndexDynamicAdaptor<Distance, DatasetAdaptor, DIM, IndexType>::KDTreeSingleIndexDynamicAdaptor(int, DatasetAdaptor&, const nanoflann::KDTreeSingleIndexAdaptorParams&, size_t)’:
/home/kbriggs/Downloads/nanoflann-master/include/nanoflann.hpp:1825:16: error: ‘log2’ is not a member of ‘std’
    treeCount = std::log2(maximumPointCount);
                ^
/home/kbriggs/Downloads/nanoflann-master/include/nanoflann.hpp:1825:16: note: suggested alternative:
In file included from /usr/include/features.h:367:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h:482,
                 from /usr/include/c++/5/bits/stl_algobase.h:59,
                 from /usr/include/c++/5/vector:60,
                 from /home/kbriggs/Downloads/nanoflann-master/include/nanoflann.hpp:49,
                 from pointcloud_kdd_radius.cpp:31:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:144:1: note:   ‘log2’
 __MATHCALL (log2,, (_Mdouble_ __x));
 ^

**Comment by jlblancoc** [comment]
Hi, 

nanoflann requires C++11 to build. Add the required flags to your compiler as needed. 
For g++, add: `-std=c++11` (or newer, C++14, etc.).

**Comment by keithbriggs** [comment]
Thanks, that works now.


Keith

________________________________
