### ISSUE TITLE
What does ANN mean?

### ISSUE THREAD

**Issue by keithbriggs** [jlblancoc/nanoflann#64]
http://jlblancoc.github.io/nanoflann/modules.html says "C++ header-only ANN library", and the term ANN appears in other places in the docs.   I thought ANN meant 'approximate nearest neighbours', but https://github.com/jlblancoc/nanoflann says "No support for approximate NN is provided".  What's going on here?

**Comment by jlblancoc** [comment]
You're totally right about the confusing name!

Indeed, the "A" means "Approximate", but it's only for "historical" / "credit" reasons, since this project born as a fork of ANN, and all the "A"-part was strip off in the fork... ;-)

**Comment by keithbriggs** [comment]
Thanks for the reply, that's clear now.


I have another question - I need an L infinity norm for my application.   I tried to code it, but I don't know if it's right because I don't understand what the accum_dist function does, and maybe it's impossible to provide such a function for the infinity norm.


Keith


________________________________

**Comment by jlblancoc** [comment]
> I have another question - I need an L infinity norm for my application

Good question. Off the top of my head, I would say a kd-tree is not suitable for L infinity norms, since it needs to evaluate distances for *any* dimension independently. 

What about an approximation where the exponent `e` of each dimension `(a_i - b_i)^e` is "large"? Taking care of not overflowing, it might be acceptable approximation.

**Comment by keithbriggs** [comment]
Yes, that might work.  However, scipy can do infinity norms, so it must be possible.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.query_ball_point.html#scipy.spatial.KDTree.query_ball_point

Keith


________________________________
