### ISSUE TITLE
CUDA capable

### ISSUE THREAD

**Issue by nitro44x** [jlblancoc/nanoflann#67]
Have you given any thought to porting this to CUDA? Perhaps not the tree construction, but being able to find the kNN of a set of points in parallel, rather than one at a time would be great!

**Comment by svenevs** [comment]
This is no small task, even just for searching.  If you wanted to do it, I encourage you use [thrust](http://thrust.github.io/).  It would probably make more sense to fork the project, and define all stl members (e.g. `std::vector`) as thrust host vectors.  You would then be able to relatively conveniently compute the KD tree on the CPU, and use simple assignments to `thrust::device_vector`'s to get the built tree over there.

That said, I'd be very surprised if you got any performance gains.  It will almost certainly be slower.  The kinds of access patterns exhibited by a KD tree are far from ideal for GPUs.  I myself have attempted this a couple times over the years, and have never gotten anything useful out of it.  You're better off using an octree.  It's not easy to engineer, but there's an excellent chapter on [octree textures](https://developer.nvidia.com/gpugems/GPUGems2/gpugems2_chapter37.html) you can work off of.  The use of textures makes things particularly well suited for GPUs.
