### ISSUE TITLE
flann submodule

### ISSUE THREAD

**Issue by patrikhuber** [jlblancoc/nanoflann#68]
Hi!

It seems like recently, flann was added as a submodule to this repo. It's not used in the `nanoflann.hpp` header, but I found some uses of flann headers in the benchmark folders.
Now as a user of just the nanoflann header, included via submodule in my own repo, it's quite annoying that now with every clone, the flann submodule is fetched through nanoflann. Even more so since it's completely unnecessary for the nanoflann library. I know that repositories can be cloned without `--recursive` and then transitive submodules will not be fetched but unfortunately this is very often not an option as other repos actually do need the submodules that they include.

I would like to propose to move the benchmark (or whichever part uses flann) to a different repo (it can be linked in the README.md here), so that users including the nanoflann repo into their repos via submodule, aren't fetching the flann code too. After all, the main reason to use nanoflann, is not to have to use flann.
For me, this is currently a reason not to upgrade nanoflann.

**Comment by jlblancoc** [comment]
You're right!! 👍 
I'll think about either using cmake to clone/download flann only if the benchmark is marked to be built (it's off by default), or moving all the benchmarks to a new repo.

**Comment by patrikhuber** [comment]
Cool! Sounds awesome :-) 👍  Looking forward to it.

Thank you,
Patrik

**Comment by pranjal-rai** [comment]
Hi @jlblancoc @patrikhuber 

I think the above mentioned feature already exists in the library and [`BUILD_BENCHMARKS`](https://github.com/jlblancoc/nanoflann/blob/master/CMakeLists.txt#L78) is OFF by deafult. Flann will be cloned only if `BUILD_BENCHMARKS` is on.

**Comment by patrikhuber** [comment]
Hi @pranjal-rai,
flann may only be built/included/installed when `BUILD_BENCHMARKS` is ON, but it is always cloned, since it is included as a [git submodule](https://github.com/jlblancoc/nanoflann/blob/c44da5d0b3712346bcea18780bafc407df6df7ae/.gitmodules#L1-L3).

**Comment by svenevs** [comment]
One thing that could be considered, though is awkward for the developers, is to move the implementation itself into its own silo repo.  Something like

```
README.md
LICENSE
nanoflann/
    nanoflann.hpp
```

Where the README basically says "use this as a git submodule in your own projects, add the root of this directory to be able to `#include <nanoflann/nanoflann.hpp>`".  Of course if users prefer `<nanoflann.hpp>` without folder scope, they can set that up too.  Then just link to the README here for tutorials / benchmarks etc.

Then add that repo as a submodule here (maybe rename this to `nanoflann-tests` and call that repository `nanoflann`).

The benefit: it keeps things very streamlined for developers using `nanoflann` in a submodule capacity, without any other testing or benchmarking files flying around.

The down side: during the initial move, you basically lose all history (if you did this, maybe link to the last commit on the file on this repo in the commit message?), and it's more cumbersome for the people maintaining `nanoflann`.

I don't really know how I feel about it, I saw the discussion and this setup came to mind, so I thought I'd offer the idea.

**Comment by patrikhuber** [comment]
@svenevs: In my opinion, tests, build files (CMake configs etc.), doxygen and all that stuff belong into the same repo than the code. perf-tests as well. In my opinion it is important to keep these things, particularly tests, right next to the library code.
What does not belong in the same repository, in my opinion, are benchmarks against other libraries, particularly if they introduce other dependencies as submodules. :-) I think this is a very clean cut, at least for me. Benchmarks are something else from the library, and I think the most simple and common-sense solution is to have these in a separate repo.

**Comment by jlblancoc** [comment]
I understand @svenevs point about the **convenience** of a minimal nanoflann repository so it can be used as a submodule in other projects, but, overall, my opinion aligns with @patrikhuber : at least, docs, and unit tests should go together with the library headers themselves, so they are always in sync. 

One thing I have doubts about and would like to hear the community opinion, before I make the move of benchmarking to its own repo: to minimize the size of this (main) repo after the move, I could do a git commits pruning, i.e. **rewriting history**, to remove all references to large files that will no longer belong to this main repo. 
* Pros: cloning time & repo size will be minimized.
* Cons: I think there is no "transparent" way to do it without forcing all current users to re-cloning from scratch...

**Comment by patrikhuber** [comment]
@jlblancoc: I just did a `git clone` of the repo (without `--recursive`, so no submodule). It took 1 second and it shows it transferred 2.14 MiB. That's very, very fast and small, so at this point I wouldn't even think about pruning :-)

**Comment by jlblancoc** [comment]
👍 I have to change my mind... working all day with @MRPT I forget small repositories still exist! XD

**Comment by svenevs** [comment]
> @MRPT I forget small repositories still exist

LOL!  Yeah this repo is really small, it makes more sense to keep everything together.  So the question I have: why did you need `flann` as a submodule in the first place?  Is it because they don't officially release CMake scripts?  The installation does come with a `pkg-config` script, which you can use in CMake (I assume you know how because of MRPT, but can elaborate if desired).

It seems pretty reasonable to assume that if somebody wants to re-benchmark, they at least know how to install `flann` on their own.

**Comment by jlblancoc** [comment]
It's much better now after the commits referenced above. 

Thanks  for the feedback! :+1:

**Comment by patrikhuber** [comment]
Thank you! :-)
