### ISSUE TITLE
documentation not reachable

### ISSUE THREAD

**Issue by psteinb** [jlblancoc/nanoflann#71]
Hi, 

[this link](http://nanoflann-reference.mrpt.org/svn/classnanoflann_1_1KDTreeSingleIndexAdaptor.html) gives me a 404 and hence is not reachable. Here is the full error report:

```
Forbidden
You don't have permission to access /svn/classnanoflann_1_1KDTreeSingleIndexAdaptor.html on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```

Can this be solved?

**Comment by svenevs** [comment]
It seems like that may be an outdated link?  It points to `nanoflann-reference.mrpt.org`, but the docs are on `jlblancoc.github.io/nanoflann`.  Maybe that's where the docs used to be?

So I think you want [these `KDTreeSingleIndexAdaptor` docs](http://jlblancoc.github.io/nanoflann/classnanoflann_1_1KDTreeSingleIndexAdaptor.html).

**Comment by jlblancoc** [comment]
Thanks for reporting 👍  
It's fixed now.

**Comment by psteinb** [comment]
thanks.
P
