### ISSUE TITLE
Modern CMake usage

### ISSUE THREAD

**Issue by stotko** [jlblancoc/nanoflann#80]
nanoflann starts to make use of modern CMake which I highly appreciate (https://github.com/jlblancoc/nanoflann/blob/master/CMakeLists.txt#L64). However, this breaks support for CMake 2.8.12 since header-only libraries/targets are a feature of CMake 3.0+ (see https://cmake.org/cmake/help/v3.0/release/3.0.0.html#commands). Unfortunately, this issue has not been caught by Travis since it uses CMake 3.9.
Furthermore, this target is also used to build nanoflann's benchmarks, but sadly not exported/installed such that users with more recent version of CMake can actually profit from this.

I would like to contribute a patch to fix this, but first wanted to get some feedback which strategy would be best to tackle the problem. Essentially, there are two possibilities:

- Bump minimum required CMake version to 3.0 (or 3.1 to get `set(CMAKE_CXX_STANDARD 11)`) and export targets such that user can also use them (see e.g. https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/).

- Export targets but guard all CMake 3.0+ stuff (`if (NOT CMAKE_VERSION VERSION_LESS 3.0)`) to also provide support for old CMake 2.8.12.

The former results in a much cleaner CMake file at the cost of dropping support for Ubuntu 14.04 LTS and folks. The latter approach has the opposite effect, i.e. more clutter but proper support. Suggestions?

Best regards,
Patrick Stotko

**Comment by patrikhuber** [comment]
My two cents: Anybody still using <CMake-3.0 should seriously consider upgrading, and it's on themselves if projects don't work anymore. I agree Ubuntu LTS's old CMake versions are a pain, but you can just download a newer cmake zip file from cmake.org, unzip it to your home directly, add it to your path, and be done with it. It's dead simple.
Project should require at least 3.2/3.3, better even 3.8.2. Seriously - move on and upgrade. It's dead simple. Just a zip file to download and unzip. Works on any system, without `sudo` rights.

**Comment by stotko** [comment]
I totally agree that users should upgrade and use more recent versions of CMake. I'm using CMake 3.10, but still need to link to third party libraries in the old fashioned way (for instance to nanoflann). That's my motivation for contributing a patch.

Ubuntu 14.04 LTS reaches EOF next year, other distros mostly use more recent [CMake versions](https://gitlab.com/CLIUtils/modern-cmake/blob/master/chapters/intro/dodonot.md). I would also suggest to require at least 3.1. Ubuntu 16.04 LTS with 3.5 should be considered the oldest supported version now that we also have 18.04 LTS. But the decision is up to @jlblancoc.

If we agree to bump the requirements, I'll propably extend this to a more general overhaul.
