### ISSUE TITLE
Visual Studio 2012, vs110

### ISSUE THREAD

**Issue by Sayantan2048** [jlblancoc/nanoflann#81]
Hi I'm getting the errors with vs110 on following lines -

* template <typename T>
struct has_resize <T, decltype((void)std::declval<T>().resize(1), 0)> : std::true_type {};
*  template <typename T>
	struct has_assign <T, decltype((void)std::declval<T>().assign(1, 0), 0)> : std::true_type {};

The error are -
* Failed to specialize function template 'add_rvalue_reference<_Ty>::type std::declval(int) throw()'
* left of '.resize' must have class/struct/union

**Comment by jlblancoc** [comment]
Closing, since it seems to be a compiler problem.
