### ISSUE TITLE
Visual Studio Warning - Possible loss of data - Assigning zeros

### ISSUE THREAD

**Issue by J-Light** [jlblancoc/nanoflann#84]
VS2015 warns of possible loss of data when assigning a zero value as the value is always int and converted to `float` or `double`. 

An easy fix would be to make the following changes to `findNeighbors` function 

```c++
auto zero = static_cast<decltype(result.worstDist())>(0);
assign(dists, (DIM > 0 ? DIM : BaseClassRef::dim), zero); // Fill it with zeros.
```

**Comment by jlblancoc** [comment]
Closed after #85
