### ISSUE TITLE
Implementation of proper deletion

### ISSUE THREAD

**Issue by JadBatmobile** [jlblancoc/nanoflann#91]
Is there any intention of implementing proper deletion in the KDTreeSingleIndexDynamicAdaptor class?

As opposed to the lazy deletion currently implemented in function removePoint()

**Comment by jlblancoc** [comment]
Hi, 
Not for now, sorry. Any help in this line would be great. 
My plan is to work on a "nanoflann v2" version in the next months, but my expected changes are mainly in: better handling of spaces with complex topologies, and a clean-up in the API. 
Cheers
