### ISSUE TITLE
What's the difference of knnSearch() and findNearest() ? 

### ISSUE THREAD

**Issue by compressible** [jlblancoc/nanoflann#92]
Seems they have the same function, but with different interface?

**Comment by jlblancoc** [comment]
This one:
``` 
 template <typename RESULTSET>
  bool findNeighbors(RESULTSET &result, const ElementType *vec,
                     const SearchParams &searchParams) const
```
returns the results via a RESULTSET object: which will do whatever with them... store them all, only keep the closest one, etc.

This one:

```
  size_t knnSearch(const ElementType *query_point, const size_t num_closest,
                   IndexType *out_indices, DistanceType *out_distances_sq,
                   const int /* nChecks_IGNORED */ = 10) const 
```

is a more specific API entrypoint, which returns the `N` closest neighbors. Internally, the latter uses the former, as you probably already saw in the code.
