### ISSUE TITLE
Segmentation fault with duplicate points

### ISSUE THREAD

**Issue by jammy4536** [jlblancoc/nanoflann#93]
I recently encountered issues when trying to incorporate this library into an SPH code, and in trying to debug (The reason for the debug is also dubious: I realised I had to search the square of the radius I was interested in), I created some duplicate points. When I try to perform a radius search on one of the points, the library gives a segmentation fault. 
Whilst it's perhaps bad to have duplicate points in the space, it is possible in SPH simulations to have points overlap (normally when the simulation goes berserk), and I don't feel it's a robust handling of what is likely a common scenario.  Surely the library should return it as any other neighbour, with a distance of 0.0. 
I am using the KDTreeVectorofVectorsAdaptor for a  std::vector<Eigen::Vector2d> data structure, should that have any influence.

**Comment by svenevs** [comment]
Shot in the dark, but it sounds like maybe you aren't using a proper aligned allocator with your `std::vector`. If you are not, you should, and this is likely the reason for the segfault (rather than the existence of duplicate points).

The segfault probably comes from deep within eigen, where it's trying to vectorize something on unaligned memory. Depending on the platform, that usually results in either a segfault or a bus error.

Hope that is useful...

**Comment by jammy4536** [comment]
I'm allocating the vector using push_back for each point. Any suggestions for aligning the allocation?

**Comment by svenevs** [comment]
It's one of the template parameters to the declaration of the vector
itself: https://eigen.tuxfamily.org/dox/group__TopicStlContainers.html

P.S. if you're using c++11 or later, use emplace_back ;)

**Comment by jammy4536** [comment]
Brilliant. I think I've got the necessary adjustments to the code (I edited the previous comment to elaborate the data structure). I will test tomorrow however and report back. At any rate, this has probably made the memory much safer regardless.

**Comment by jammy4536** [comment]
Yep, that seems to have solved it! A huge thanks for your help!

**Comment by svenevs** [comment]
Excellent! If it makes you feel better, I learned about these things (aligned allocator / operator needed) from similar segfaults, but now that you know to keep an eye out for it...if you forget in the future you'll know the fix almost immediately :)
