### ISSUE TITLE
MSVC compiler warnings (C4267) caused by conversion from size_t to int on 64-bit platforms.

### ISSUE THREAD

**Issue by dbrookes96** [jlblancoc/nanoflann#95]
Related to issue #11.
nanoflann has a number of implicit conversions from size_t to int causing the compiler warning ([C4267](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4267)) by Visual Studio's compiler. As per the linked Microsoft doc this warning would only trigger on 64-bit systems. 
An example of this is in the L1_Adaptor, L2_Adaptor, L2_Simple_Adaptor and SO2_Adaptor's evalMetric functions, calls are made to kdtree_get_pt(size_t, int) with a size_t as the second argument. There are also a number of other places where such a thing occurs such as in the constructor for KDTreeSingleIndexDynamicAdaptor the size_t value returned from kdtree_get_pount_count() is assigned to an int value. 
The issue is also present inversely where int values are sometimes cast to size_t which may also cause logic issues (no compiler warning however).
I would be happy to have a look at some of the changes required given some guidance from the author(s).

**Comment by jlblancoc** [comment]
Should be fixed now... give it a try and see the diff of https://github.com/jlblancoc/nanoflann/commit/7011ba39af2c9f4caac641bdffc3df3453c22b3e to see what changes may be required on your code. 
Cheers

**Comment by dbrookes96** [comment]
Thanks Jose.
Updated to the 1.3 release and all the warnings are fixed :)
