### ISSUE TITLE
M_PI is undefined if <cmath> is included before nanaflann.h without defining _USE_MATH_DEFINES

### ISSUE THREAD

**Issue by cmorrison31** [jlblancoc/nanoflann#96]
On MSVC the _USE_MATH_DEFINES macro is inside of the <cmath> include guards. This means that if you use <cmath> in a header which ends up being included directly (or transitively) before nanoflann.h M_PI will not be defined and compilation fails. It can be difficult to track down exactly which instance of #include <cmath> is first if multiple headers use it and each other. Defining _USE_MATH_DEFINES globally leads to redefinition errors.

Since this is a C++11 library, a good solution in my opinion would be to replace M_PI with a constexpr value. I'd be happy to submit a simple pull request if this solution is amenable.

**Comment by jlblancoc** [comment]
Normally I would export the `_USE_MATH_DEFINES ` macro via the library `FooConfig.cmake` file... but nanoflann is intended to be used as easily as possible, just dropping the .hpp file wherever. 
So: ok, go on with a PR... thanks!
